version: '3'
services:

  flask:
    build: .
    container_name: flask
#    restart: unless-stopped
    #environment:
      #APP_ENV: "prod"
      #APP_DEBUG: "False"
      #APP_PORT: 5000
      #MONGODB_DATABASE: flaskdb
      #MONGODB_USERNAME: admin
      #MONGODB_PASSWORD: 12345
      #MONGODB_HOSTNAME: mongodb
#    volumes:
#      - appdata:/var/www
    depends_on:
      - mongodb
    ports:
      - 5000:5000


  mongodb:
    image: mongo:5.0
    container_name: mongodb
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: flaskdb
#      MONGODB_DATA_DIR: /data/db
#    volumes:
#      - mongodbdata:/data/db
    ports:
      - 27017:27017


volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
  nginxdata:
    driver: local
