apiVersion: v1
kind: Service
metadata:
  name: {{.Values.servicelabel.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
  selector:
    app: {{ .Values.deploylabel.name }}
