apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ravivecho.fullname" . }}
  labels:
    app: {{.Values.deploylabel.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{.Values.deploylabel.name }}
  template:
    metadata:
      labels:
        app: {{.Values.deploylabel.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
          - name: MONGODBURL
            valueFrom:
              secretKeyRef:
                name: mongouri
                key: uri
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

