apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio
  namespace: default
  annotations:
    argocd-image-updater.argoproj.io/image-list: portfolio=<AWS ID>.dkr.ecr.eu-central-1.amazonaws.com/portfolio
    argocd-image-updater.argoproj.io/portfolio.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/nadivravivz/portfolio.git
    targetRevision: HEAD
    path: portfoliochart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
