apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portfolio-prod
spec:
  secretName: portfolio-prod-certificate
  issuerRef:
    name: letsencrypt-prod
  emailAddresses:
  - blabla@blabla.com
