apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # nginx.ingress.kubernetes.io/rewrite-target: /$1 
spec:
  tls:
  - hosts:
      - ad7e9104de7d04c7abe4c4c62a4a65c0-1420413677.eu-central-1.elb.amazonaws.com
    secretName: ravivportfolio-tls
  rules:
  - host: ad7e9104de7d04c7abe4c4c62a4a65c0-1420413677.eu-central-1.elb.amazonaws.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: portfolio-service
            port:
              number: 80


