apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # nginx.ingress.kubernetes.io/rewrite-target: /$1 
spec:
  tls:
  - hosts:
      - ravivportfolio.tk
    secretName: ravivportfolio-tls
  rules:
  - host: ravivportfolio.tk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: portfolio-service
            port:
              number: 80


